version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - jenkins_cami:/var/jenkins_home

volumes:
  jenkins_cami:
    name: jenkins_cami
